# Generated by Django 4.1.1 on 2023-07-06 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('theme', models.TextField()),
                ('room_width', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('room_height', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
