# Generated by Django 4.1.1 on 2023-07-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='illustrations')),
                ('date_painted', models.DateField()),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exhibition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
