# Generated by Django 4.1.1 on 2023-08-22 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_userprofile_exhibition_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='wall_color',
            field=models.TextField(default='ffffff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
