# Generated by Django 4.1.1 on 2023-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exhibition_wall_color_alter_userprofile_is_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(to='api.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='wall_color',
            field=models.TextField(default='#ffffff'),
        ),
    ]
