# Generated by Django 4.1.1 on 2023-08-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_liked_alter_exhibition_wall_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='likes',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exhibition')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
