# Generated by Django 4.1.1 on 2023-08-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_likes_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('exhibition', 'user_profile')},
        ),
    ]
